apiVersion: v1
kind: Service
metadata:
  name: {{ include "glob.fullname" . }}
  labels:
    {{- include "glob.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  selector:
    {{- include "glob.selectorLabels" . | nindent 4 }}
